### ISSUE TITLE
Support other delimiters

### ISSUE THREAD

**Issue by arve0** [pnewell/markdown-it-span#2]
Hi! I have a standing issue (https://github.com/arve0/markdown-it-attrs/issues/38) that can be solved by this plugin if it also supported the [pandoc syntax for spans](http://pandoc.org/MANUAL.html#extension-bracketed_spans), using brackets `[spanned text]`.

Would you be interested in adding that, or approve any PRs with the extra functionality? For example, by enabling different delimiters like this:

```js
md.use(span, {
  leftDelimiters: '[',
  rightDelimiters: ']',
})
```

Of course, it should not mangle with image- or link-parsing. I'm not sure if that is feasible, read your code, but have not grokked the parser-part of markdown-it just yet.

**Comment by Connum** [comment]
That would be so great if this could be achieved combining the two plugins! Would be a live-safer for a current project I'm working on... :)

**Comment by mb21** [comment]
You might like https://github.com/mb21/markdown-it-bracketed-spans
